spring:
  application:
    name: GreenEcoMall
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: mLURIDZFPcYHEOXSnMjgmKwaFHHsVhlX
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: false

jwt:
  secret: greenecomall-super-secret-key-must-be-at-least-256-bits-long-for-hs256
  access-token-expiration: 9000000       # 15 minutes
  refresh-token-expiration: 2592000000  # 30 days

app:
  base-url: ${APP_BASE_URL:https://green-eco-mall-client.up.railway.app}
  admin:
    phone: ${ADMIN_PHONE:+996700000000}
    password: ${ADMIN_PASSWORD:admin123}
    referral-code: ${ADMIN_REFERRAL:GEMADMIN}
  otp:
    expiration-minutes: 5
    max-requests-per-hour: 5
  payment:
    qr-expiration-minutes: 30
  finik:
    api-key: 0c0z3IkpXz294LV7YslMK2PIqrQtCGcR4mDXPyq8
    account-id: 717233df-1a6b-4f5d-ba95-2d311eb8d302
    private-key-path: classpath:private_key.pem
    base-url: https://api.acquiring.averspay.kg
    webhook-url: https://greenecomall-dev.up.railway.app/api/payment/webhook
    redirect-url: https://green-eco-mall-client.up.railway.app

minio:
  url: ${AWS_ENDPOINT_URL:https://fly.storage.tigris.dev}
  access-key: ${AWS_ACCESS_KEY_ID:changeme}
  secret-key: ${AWS_SECRET_ACCESS_KEY:changeme}
  bucket: ${AWS_S3_BUCKET_NAME:greenecomall}
  region: ${AWS_DEFAULT_REGION:auto}

sms:
  smspro:
    enabled: false
    url: ${SMSPRO_URL:https://smspro.nikita.kg/api/message}
    login: Cholpon123456
    password: 6Jf8
    sender: BilgirimKG

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN:8681208071:AAFmF6OFuS8YgQJ87_a0sA733AP4xFKTA68}
  dev-chat-id: ${TELEGRAM_DEV_CHAT_ID:7838639205}


logging:
  level:
    greenecomall: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: ERROR

server:
  port: 8080
