spring:
  application:
    name: GreenEcoMall
  datasource:
    url: jdbc:postgresql://localhost:5432/synamyk
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: false

jwt:
  secret: greenecomall-super-secret-key-must-be-at-least-256-bits-long-for-hs256
  access-token-expiration: 900000       # 15 minutes
  refresh-token-expiration: 2592000000  # 30 days

app:
  base-url: ${APP_BASE_URL:https://greenecomall.kg}
  admin:
    phone: ${ADMIN_PHONE:+996700000000}
    password: ${ADMIN_PASSWORD:admin123}
    referral-code: ${ADMIN_REFERRAL:GEMADMIN}
  otp:
    expiration-minutes: 5
    max-requests-per-hour: 5
  payment:
    qr-expiration-minutes: 30
  finik:
    api-key: ${FINIK_API_KEY:JtsoRKA2il3kCGeNREQMNgPbCpjcP4a2PDlfLUV3}
    account-id: ${FINIK_ACCOUNT_ID:9391947c-fd6e-4aae-81b2-da794d0d1e88}
    private-key-path: classpath:finik_private.pem
    base-url: https://api.acquiring.averspay.kg
    merchant-category-code: "0742"
    qr-name-en: "GreenEcoMall"
    webhook-url: ${APP_BASE_URL:https://greenecomall.kg}/api/payment/webhook

sms:
  smspro:
    enabled: true
    url: ${SMSPRO_URL:https://smspro.nikita.kg/api/message}
    login: Cholpon123456
    password: 6EX5vJf8
    sender: BilgirimKG


logging:
  level:
    greenecomall: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: ERROR

server:
  port: 8080
